### ISSUE TITLE
Turn off ads from search results

### ISSUE THREAD

**Issue by jayunit100** [grpc/grpc.io#1038]
https://grpc.io/search/?q=watch

seems to return random stuff from the internet :) 

<img width="848" alt="image" src="https://user-images.githubusercontent.com/826111/185615039-6538694f-fefe-48fd-be97-660e1f66ce03.png">

**Comment by drfloob** [comment]
I'm not sure it's possible to remove ads from the site search results. @chalin do you know if we can?

**Comment by chalin** [comment]
Yes it is possible, we did this not too long ago for the opentelemetry.io and the docsy.dev.

@ejona86 @thisisnotapril: do you know who owns the Programmable Search Engine account. Either you need to get grpc.io recognized as an open source project, or you need to get it whitelisted internally at Google so that you can have the display of ads turned off.

/cc @caniszczyk @emckean

**Comment by emckean** [comment]
@thisisnotapril I'll ping you the Buganizer link :)

**Comment by chalin** [comment]
Any update on this @emckean @thisisnotapril?

**Comment by easwars** [comment]
Any update on this @emckean @thisisnotapril?

**Comment by emckean** [comment]
Hi folks! I couldn't find the original bug, I have opened another one. Will keep you posted. Thanks!

**Comment by emckean** [comment]
Hi, this should be turned off now. Sorry for the delay!

**Comment by shivaspeaks** [comment]
Closing this issue as the ads are turned off.

We don't see ads now: 
<img width="1728" alt="Screenshot 2024-11-27 at 12 32 43 PM" src="https://github.com/user-attachments/assets/36d4ed90-d0b7-4aad-8fc0-8df4caa00852">
