### ISSUE TITLE
Quick start document, should we change `make -j` to `make -j $(nproc)`?

### ISSUE THREAD

**Issue by rickyrick2002** [grpc/grpc.io#1041]
`make -j` halts the machine when buiding.

**Comment by drfloob** [comment]
This issue has come up a few times before. See https://github.com/grpc/grpc.io/pull/983 and https://github.com/grpc/grpc.io/issues/740. `nproc` is not cross-platform, so mac users would be ill-served by this change. And fixing it to a specific value is probably unwise. As others have suggested, I'd recommend leaving it as is, since OOMs should be rare, and users can plug in their own job count as needed.
