### ISSUE TITLE
gRPConf 2022 Page

### ISSUE THREAD

**Issue by temawi** [grpc/grpc.io#1053]
This is a tracking issue for creating a subpage for the gRPC conference that will be happening as part of KubeCon on 10/24/22.

Rough initial plan is to make a separate landing page that has information about the schedule, speakers, codelabs etc. It would also be linked to from the main grpc.io page.

**Comment by temawi** [comment]
FYI @ejona86 @chalin

**Comment by chalin** [comment]
Hi @temawi - As you probably already know, 2020 gRPConf had (and still has) its own separate announcement page here:

- https://events.linuxfoundation.org/grpc-conf/

Maybe it would make sense to populate that section of the events.linuxfoundation.org site with gRPConf 2022 info? (I understand that the context was different in 2020, as it was a fully virtual, separate event).

The gRPConf 2022 schedule page under KubeCon + CNC 2022 is here:

- https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/schedule/

Since this page _will_ for sure be updated to contain the gRPConf'22 schedule, why duplicate it by publishing info via a separate page on the grpc.io website -- or am I misunderstanding the intent of this tracking issue?

Regardless of what happens, I think that, at a minimum, https://events.linuxfoundation.org/grpc-conf/ should be updated to point to the 2022 gRPConf. Don't you agree @thisisnotapril?

/cc @caniszczyk

**Comment by temawi** [comment]
Thanks for the feedback! I'm starting to look at this without any previous context. I think having all this detail on the grpc-conf/ page and then linking to it from the main schedule would be a good approach. 

@thisisnotapril do know what the process would be to get that grpc-conf/ page updated or a new one created for this year?

**Comment by chalin** [comment]
> ... do know what the process would be to get that grpc-conf/ page updated

I had a contact, but they've left. I'll inquire and get back to you @temawi.

**Comment by chalin** [comment]
Email sent, cc @thisisnotapril and @ejona86.

**Comment by chalin** [comment]
Not that https://events.linuxfoundation.org/grpc-conf/ has 2022 conf info, maybe it's time to add a banner announcing gRPConf on the website?

**Comment by temawi** [comment]
Maybe wait until we have the finalized schedule up there as well? I'm hoping it wouldn't take too long.

Where were you thinking the banner would go?

**Comment by chalin** [comment]
We have a banner "placeholder". When enabled the banner appears at the top of the page. E.g., see:

- #284 - has screenshots
- Preview: https://deploy-preview-284--grpc-io.netlify.app/

**Comment by dfawley** [comment]
Can this be closed now that gRPConf is over?  Or do we want to put up artifacts from that, still?  @temawi @chalin

**Comment by temawi** [comment]
Yes, this ended up being just a Google site.
