### ISSUE TITLE
error: 'google/protobuf/compiler/code_generator.h' file not foundrt

### ISSUE THREAD

**Issue by baihe5910** [grpc/grpc.io#1148]
sudo make install-plugin

then error :

fatal error: 'google/protobuf/compiler/code_generator.h' file not found

**Comment by dfawley** [comment]
This seems to be about grpc-web.  Can you help @sampajano?

**Comment by sampajano** [comment]
@dfawley thanks for the CC!

---

@baihe5910 Hi! I think the problem is that you have not checked out the submodules, which is our build dependency.

Run the following command and it should fix things for you:

```
./scripts/init_submodules.sh
```

Hope it works!

---

Btw could you give a pointer to see where you got the instruction to run the command on grpc.io? Maybe we can update the documentations.

If it's grpc-web specific issues, please file them directly at at https://github.com/grpc/grpc-web directly next time — it would help save some triaging time.

Thanks! :)
