### ISSUE TITLE
Java quick start doesn't work

### ISSUE THREAD

**Issue by unfode** [grpc/grpc.io#1150]
**Issue description**

When I run `./gradlew installDist` as per [the Java quick start guide](https://grpc.io/docs/languages/java/quickstart/), I get the following error:

![image](https://github.com/grpc/grpc.io/assets/95689995/f3700628-8868-4218-a2d1-9d7bace8ba25)

**Steps to reproduce the issue**

Same as the quick start guide.

**Expected behavior**

Success as described in the quick start guide.

**Screenshots**

See above.

**Desktop (if relevant):**
 - OS: MacOS 13.3.1

**Comment by temawi** [comment]
I just tried the steps (on mac as well), and the `./gradlew installDist` step worked for me.

Looks like you didn't follow the git checkout step accurately as you don't seem to have the 1.56 release. Your error refers to 1.57.0-SNAPSHOT, which is what it is on the master branch. SNAPSHOT versions the build artifacts are not available to download from a remote repository, which is why you are seeing the error. They need to be built locally.

You have two options:

1. Check out a released version like the latest, v.1.56.0
2. If you really need to work with SNAPSHOT versions (you probably don't) then you need to follow the steps in [COMPILING.md](https://github.com/grpc/grpc-java/blob/master/COMPILING.md)

**Comment by unfode** [comment]
Thank you! It works when I use the right branch!
