### ISSUE TITLE
Code snippets overextend layout on narrow browser windows

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc.io#185]
**Issue description**
Many pages are truncated on the left or right when using a window ~1024px wide.

**Steps to reproduce the issue**
1. Go to https://grpc.io/docs/quickstart/java/
2. Shrink window size

**Desktop (if relevant):**
 - OS: Linux
 - Browser: Chrome

**Additional info**
My browser window tends to stay a bit over 1024 pixels wide, as most content stops being able to use windows over that width.

I just noticed pages where the right-side content was cropped:
https://grpc.io/docs/quickstart/java/
https://grpc.io/docs/guides/auth/

Unless it is the left-side content, because of a fragment:
https://grpc.io/docs/guides/auth/#supported-auth-mechanisms

While very wide-spread, this poor handling doesn't seem universal. Most small pages are fine, and even these:
https://grpc.io/docs/guides/
https://grpc.io/docs/reference/go/generated-code/

I think this is caused by wide code snippets. For example, Ruby, C#, Node.js, Java snippets have long lines on this page:
https://grpc.io/docs/guides/auth/#ruby

Ideally code snippets would scroll instead of causing the page to be truncated. But we also may want to shorten the line length of many of the snippets. Surely we don't need 107 characters on a line.

That may be made worse by the overall large text on the site and generous margin around the toc navigation.

**Comment by chalin** [comment]
Actually, regular text overextends too; here's a screenshot (note the paragraph text "Download the exa|":

<img width="1026" alt="Screen Shot 2020-04-13 at 16 51 21" src="https://user-images.githubusercontent.com/4140793/79160050-2a3ef180-7da7-11ea-8593-d746096ed79f.png">

Is this the kind of issue that you are referring to?

It also happens when there is no left-nav:

![image](https://user-images.githubusercontent.com/4140793/79160220-6bcf9c80-7da7-11ea-9cfa-ac9f654756ad.png)

**Comment by chalin** [comment]
Thanks for the detailed report. You seem to be right: if I delete the extra long lines of code from https://grpc.io/docs/quickstart/java/, it fixes the issue (the prose isn't overextended).

> Ideally code snippets would scroll ...

The code snippets do scroll along the (left-right axis). Will investigate further to identify the cause.

**Comment by ejona86** [comment]
I did see that code snippets _eventually_ scroll, but it was clearly not happening soon enough. Things are looking good now. Excellent!

**Comment by chalin** [comment]
Reopening since #186 isn't a proper fix, in particular it is the cause of #188 -- context https://github.com/grpc/grpc.io/pull/186#discussion_r506604156.

**Comment by chalin** [comment]
The cause of the problem is that excessively wide code blocks inside of a bulma `column` cause the entire column content to be widened, even if the code block (`pre` element) has it's `overflow-x` attribute appropriately set. See https://github.com/jgthms/bulma/issues/2616 and https://github.com/jgthms/bulma/issues/1540.
