### ISSUE TITLE
Make protoc more accessible in Quick Start (Go) guide

### ISSUE THREAD

**Issue by jrefior** [grpc/grpc.io#383]
Currently the first and only `protoc` example in [`docs/languages/go/quickstart/`](https://grpc.io/docs/languages/go/quickstart/) is this:

```
$ ( cd ../../cmd/protoc-gen-go-grpc && go install . )
$ protoc \
  --go_out=Mgrpc/service_config/service_config.proto=/internal/proto/grpc_service_config:. \
  --go-grpc_out=Mgrpc/service_config/service_config.proto=/internal/proto/grpc_service_config:. \
  --go_opt=paths=source_relative \
  --go-grpc_opt=paths=source_relative \
  helloworld/helloworld.proto
```

There is no explanation of the arguments. No resource is offered/linked where one can learn more about `protoc` parameters for Go gRPC projects. E.g. where did the path `Mgrpc/service_config/service_config.proto` come from? It seems to me it would be difficult for someone who isn't already an expert to go from this guide to generating code in a new project they start from scratch.

Perhaps an additional, more minimalist example, intended for new projects, would be helpful? Or maybe a link to a new doc page, `docs/languages/go/protoc`, an official guide to using `protoc` for Go gRPC projects?

Possibly related: #298

**Comment by ericgribkoff** [comment]
cc @dfawley

**Comment by dfawley** [comment]
cc @chalin 

We don't need that parameter; we should remove it.

Also, https://github.com/grpc/grpc-go/issues/3669 appears to be approaching something agreeable, so we will need to start talking about updates to the documentation for the new API fairly soon.

**Comment by chalin** [comment]
@dfawley comments:

> We don't need that parameter; we should remove it.

Oh, ok!

For context: when working on #319, I used the command arguments from https://github.com/grpc/grpc-go/blob/master/regenerate.sh#L89-L107.

I just stepped through the quick start, using simplified `protoc` arguments, and it seems to work just fine -- see #400.

@jrefior wrote:

> There is no explanation of the arguments.

You are right. PR #400 simplifies the arguments, hopefully enough to your liking.

As you've probably seen already: there is a note in the quick start text that explains that "we are in the process of transitioning to a new Go protoc plugin" (which was meant to explain why there are currently twice as many arguments as there will eventually be):

> ![image](https://user-images.githubusercontent.com/4140793/93514267-ff783c80-f8f4-11ea-921a-9c707d6c3ff2.png)

Perhaps the problem is that the note should have appeared before the `protoc` command. I've moved it there in #400.
