### ISSUE TITLE
Blog mentions "Optimizing gRPC Part 3" but there is no such entry

### ISSUE THREAD

**Issue by asarkar** [grpc/grpc.io#388]
URL: https://grpc.io/blog/optimizing-grpc-part-2/

> In Part 3, we will optimize the code even further. 2,400 RPC/s is just the beginning!

But there is no part 3 at https://grpc.io/blog/optimizing-grpc-part-3/

**Comment by chalin** [comment]
Pat 2 of the "optimizing gRPC" blog entry series mentions a "part 3", but no such page exists. I'll edit the page to avoid raising false expectations.

Btw, I changed the issue title because there is no **link** in the site to a "Part 3" page, so technically is isn't a "page not found error" if someone manually creates a link to a page that doesn't exist 😄

**Comment by chalin** [comment]
@ejona86 et all. Folks seem to be reading https://grpc.io/blog/optimizing-grpc-part-2, reaching end of the article with the (plain) text that refers to part 3, and then manually editing the page URL in an attempt to access part 3. The resulting URL, https://grpc.io/blog/optimizing-grpc-part-3/, is currently the 4th top 404.

**Comment by ejona86** [comment]
I think it is fair to assume that the part 3 would have been posted since 2018 when part 2 was published. I don't recall what happened to it...
