### ISSUE TITLE
Drop the site's release file

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#502]
https://grpc.io/release yields the [grpc/grpc release](https://github.com/grpc/grpc/releases) with which the [site was configured](https://github.com/grpc/grpc.io/blob/main/config.yaml).

- Is this site feature used anywhere?
- Why single out `grpc/grpc` as opposed to, say, Java or Go?

**Comment by ejona86** [comment]
@jtattermusch can answer best. For reference: https://github.com/grpc/grpc/pull/21891

**Comment by chalin** [comment]
Very interesting background reading! Thanks @ejona86.

Since #79 eliminated uses of `$(curl -L https://grpc.io/release)`, can we now eliminate https://grpc.io/release, or is it used elsewhere?

**Comment by jtattermusch** [comment]
I think the grpc.io release file might not be used anymore, but TBH I'm not sure and there's a bunch or internal docs (especially the release process docs) one would need to review/update first.

What would we gain by dropping the release file? If there's some significant gain from that, we can take the time and double check that the file is now really unnecessary. Otherwise I'm not sure it's worth doing the work.

**Comment by chalin** [comment]
Thanks for the feedback @jtattermusch.

Regarding gains: as part of the migration to docsy there'll be some cleanup done. If this release URL isn't being used, then it's like dead code -- it adds cruft w/o value. There's enough complexity in this site w/o having to keep unused features.

Ok, let's put this on hold for now. I'll revisit later after the docsy migration.

**Comment by jtattermusch** [comment]
I've investigated the use of the grpc.io/release file and it seems that we can get rid of it.

The only use I've found is in the go/grpc-release doc (internal only) and I can remove those references once a PR exists to remove the logic for generating the grpc.io/release content.

**Comment by chalin** [comment]
> ... I can remove those references once a PR exists to remove the logic for generating the grpc.io/release content.

Done, see #542
