### ISSUE TITLE
Site not building under macOS: "pipe failed" error

### ISSUE THREAD

**Issue by cxsu** [grpc/grpc.io#585]
There are the following problems (only from MacOS):
google/docsy-example/issues/89

As a temporary measure, you can execute the command below.

```sh
hugo server --watch=false
```

And for those who contribute for the first time, I'd like to specify the command below.

```md
git submodule update --init --recursive --depth 1
```

I'd appreciate it if you'd consider it.

**Comment by veblush** [comment]
@chalin Can you take a look at this?

**Comment by chalin** [comment]
Thanks for raising the issue @cxsu. Since the time that you opened this issue, a macOS-specific workaround has been proposed, for details see https://github.com/google/docsy-example/issues/89#issuecomment-758311888.

I've hit max-file-descriptor (FD) limit issues under macOS (too) many times before (on other projects). I'm not seeing the issue that is referred to by https://github.com/google/docsy-example/issues/89 because my maxfiles etc. limits have already been adjusted. 

I'll be addressing your second point via #594 (though, FYI, I'm not inclined to limit the depth).

Closing. Comment here if you still have issues after adjusting those maxfiles limits on your system.

**Comment by chalin** [comment]
@cxsu - FYI, I've updated the instructions to include the `--depth 1` flag, as you suggested; see #622.
